'use strict';

const fsp = require('fs').promises;
const path = require('path');
const { shell, safeStorage } = require('electron');

class AuthService {
  constructor(app, configStore, logger, notify) {
    this.configStore = configStore; this.logger = logger; this.notify = notify;
    this.file = path.join(app.getPath('userData'), 'accounts.json');
    this.store = { activeId: '', accounts: [] }; this.session = null; this.loginController = null;
  }
  canPersistSecrets() { return safeStorage.isEncryptionAvailable(); }
  encrypt(text) { return text && this.canPersistSecrets() ? `safe:${safeStorage.encryptString(text).toString('base64')}` : ''; }
  decrypt(value) {
    if (!value) return '';
    if (value.startsWith('safe:')) return safeStorage.decryptString(Buffer.from(value.slice(5), 'base64'));
    if (value.startsWith('plain:')) return Buffer.from(value.slice(6), 'base64').toString('utf8');
    return '';
  }
  async readStore() { try { this.store = JSON.parse(await fsp.readFile(this.file, 'utf8')); } catch { this.store = { activeId: '', accounts: [] }; } if (!Array.isArray(this.store.accounts)) this.store.accounts = []; }
  async writeStore() { await fsp.mkdir(path.dirname(this.file), { recursive: true }); const tmp = `${this.file}.tmp`; await fsp.writeFile(tmp, JSON.stringify(this.store, null, 2), 'utf8'); await fsp.rename(tmp, this.file); }
  publicAccount() { return this.session ? { type: 'microsoft', name: this.session.name, id: this.session.id, skins: this.session.skins || [] } : null; }
  listAccounts() { return (this.store.accounts || []).map((a) => ({ id: a.id, name: a.name, type: 'microsoft', active: a.id === this.store.activeId, persisted: !!a.refreshToken })); }
  clientId() { const id = this.configStore.get().microsoftClientId; if (!id) throw new Error('Microsoft Client ID ayarlanmamış. Dih geliştirici ayarından public-client Client ID girilmeli.'); return id; }
  async postForm(url, form, signal) { const response = await fetch(url, { method: 'POST', signal, headers: { 'Content-Type': 'application/x-www-form-urlencoded' }, body: new URLSearchParams(form) }); const json = await response.json().catch(() => ({})); return { response, json }; }
  async loadStored() { await this.readStore(); const active = this.store.accounts.find((a) => a.id === this.store.activeId) || this.store.accounts.find((a) => a.refreshToken); if (!active?.refreshToken) return null; try { const session = await this.refresh(this.decrypt(active.refreshToken), false); this.session = session; await this.persistSession(session); this.notify('auth-changed', this.publicAccount()); return this.publicAccount(); } catch (e) { this.logger.warn('Kayıtlı Microsoft oturumu yenilenemedi', e?.message || ''); return null; } }
  cancelLogin() { if (this.loginController) { this.loginController.abort(); this.loginController = null; return true; } return false; }
  async login() { if (this.loginController) throw new Error('Microsoft giriş işlemi zaten devam ediyor.'); const controller = new AbortController(); this.loginController = controller; try { const clientId = this.clientId(); const scope = 'XboxLive.signin offline_access'; const { response, json } = await this.postForm('https://login.microsoftonline.com/consumers/oauth2/v2.0/devicecode', { client_id: clientId, scope }, controller.signal); if (!response.ok) throw new Error(json.error_description || 'Microsoft device-code alınamadı.'); this.notify('auth-device-code', { userCode: json.user_code, verificationUri: json.verification_uri, message: json.message }); await shell.openExternal(json.verification_uri); const deadline = Date.now() + Number(json.expires_in || 900) * 1000; let interval = Number(json.interval || 5) * 1000; let token; while (Date.now() < deadline) { await new Promise((resolve, reject) => { const t = setTimeout(resolve, interval); controller.signal.addEventListener('abort', () => { clearTimeout(t); reject(Object.assign(new Error('Microsoft girişi iptal edildi.'), { name: 'AbortError' })); }, { once: true }); }); const polled = await this.postForm('https://login.microsoftonline.com/consumers/oauth2/v2.0/token', { grant_type: 'urn:ietf:params:oauth:grant-type:device_code', client_id: clientId, device_code: json.device_code }, controller.signal); if (polled.response.ok) { token = polled.json; break; } if (polled.json.error === 'authorization_pending') continue; if (polled.json.error === 'slow_down') { interval += 5000; continue; } if (polled.json.error === 'authorization_declined') throw new Error('Microsoft girişi iptal edildi.'); throw new Error(polled.json.error_description || polled.json.error || 'Microsoft giriş hatası.'); } if (!token) throw new Error('Microsoft giriş süresi doldu.'); return await this.finishMicrosoft(token, true, controller.signal); } finally { this.loginController = null; } }
  async refresh(refreshToken, persist = true) { if (!refreshToken) throw new Error('Yenileme anahtarı bulunamadı.'); const { response, json } = await this.postForm('https://login.microsoftonline.com/consumers/oauth2/v2.0/token', { client_id: this.clientId(), grant_type: 'refresh_token', refresh_token: refreshToken, scope: 'XboxLive.signin offline_access' }); if (!response.ok) throw new Error(json.error_description || 'Microsoft token yenilenemedi.'); return this.finishMicrosoft(json, persist, new AbortController().signal); }
  async finishMicrosoft(msToken, persist, signal) { const { MicrosoftAuthenticator, MojangClient } = await import('@xmcl/user'); const auth = new MicrosoftAuthenticator({ fetch }); const { minecraftXstsResponse } = await auth.acquireXBoxToken(msToken.access_token, signal); const claim = minecraftXstsResponse?.DisplayClaims?.xui?.[0]; if (!claim) throw new Error('Xbox Live kimlik bilgisi alınamadı.'); const mcAuth = await auth.loginMinecraftWithXBox(claim.uhs, minecraftXstsResponse.Token, signal); const mojang = new MojangClient({ fetch }); const ownership = await mojang.checkGameOwnership(mcAuth.access_token, signal); if (!ownership?.items?.length) throw new Error('Bu Microsoft hesabında Minecraft: Java Edition lisansı bulunamadı.'); const profile = await mojang.getProfile(mcAuth.access_token, signal); const session = { type: 'microsoft', name: profile.name, id: profile.id, accessToken: mcAuth.access_token, refreshToken: msToken.refresh_token || '', expiresAt: Date.now() + Number(mcAuth.expires_in || 86400) * 1000, skins: profile.skins || [] }; this.session = session; if (persist) await this.persistSession(session); this.notify('auth-changed', this.publicAccount()); return session; }
  async persistSession(session) { await this.readStore(); const encrypted = this.encrypt(session.refreshToken); const item = { type: 'microsoft', id: session.id, name: session.name, refreshToken: encrypted, updatedAt: new Date().toISOString() }; const index = this.store.accounts.findIndex((a) => a.id === session.id); if (index >= 0) this.store.accounts[index] = item; else this.store.accounts.push(item); this.store.activeId = session.id; await this.writeStore(); if (!encrypted) this.logger.warn('OS güvenli anahtar deposu kullanılamıyor; Microsoft refresh token diske kaydedilmedi.'); }
  async select(id) { await this.readStore(); const account = this.store.accounts.find((a) => a.id === id); if (!account) throw new Error('Hesap bulunamadı.'); const token = this.decrypt(account.refreshToken); if (!token) throw new Error('Bu hesabın güvenli oturumu saklanmamış; yeniden giriş yap.'); const session = await this.refresh(token, false); this.session = session; await this.persistSession(session); return this.publicAccount(); }
  async remove(id) { await this.readStore(); this.store.accounts = this.store.accounts.filter((a) => a.id !== id); if (this.store.activeId === id) { this.store.activeId = ''; this.session = null; } await this.writeStore(); this.notify('auth-changed', this.publicAccount()); return this.listAccounts(); }
  async ensureSession() { if (this.session?.accessToken && this.session.expiresAt > Date.now() + 120000) return this.session; const restored = await this.loadStored(); if (restored && this.session) return this.session; throw new Error('Minecraft oynamak için önce Microsoft hesabınla giriş yap.'); }
  async logout() { this.session = null; this.store.activeId = ''; await this.writeStore().catch(() => {}); this.notify('auth-changed', null); }
}
module.exports = { AuthService };
