'use strict';
const fs = require('fs');
const path = require('path');
const defaults = require('../shared/defaults');
function clone(value) { return JSON.parse(JSON.stringify(value)); }
function merge(base, patch) { if (!patch || typeof patch !== 'object' || Array.isArray(patch)) return patch === undefined ? clone(base) : patch; const out = { ...(base || {}) }; for (const [key, value] of Object.entries(patch)) { if (value && typeof value === 'object' && !Array.isArray(value) && base?.[key] && typeof base[key] === 'object' && !Array.isArray(base[key])) out[key] = merge(base[key], value); else out[key] = value; } return out; }
function readJson(file) { try { return JSON.parse(fs.readFileSync(file, 'utf8')); } catch { return {}; } }
class ConfigStore {
  constructor(app) { this.app = app; this.file = path.join(app.getPath('userData'), 'config.json'); this.data = this.load(); this.validate(); }
  projectConfig() { const candidates = [process.env.DIH_CONFIG, path.join(typeof this.app.getAppPath === 'function' ? this.app.getAppPath() : process.cwd(), 'dih.config.json'), process.resourcesPath ? path.join(process.resourcesPath, 'dih.config.json') : ''].filter(Boolean); for (const file of [...new Set(candidates)]) { if (fs.existsSync(file)) return readJson(file); } return {}; }
  load() { return merge(merge(defaults, this.projectConfig()), readJson(this.file)); }
  get() { return clone(this.data); }
  set(patch) { this.data = merge(this.data, patch || {}); this.validate(); fs.mkdirSync(path.dirname(this.file), { recursive: true }); const tmp = `${this.file}.tmp`; fs.writeFileSync(tmp, JSON.stringify(this.data, null, 2), 'utf8'); fs.renameSync(tmp, this.file); return this.get(); }
  validate() { const clamp = (n, min, max, fallback) => Number.isFinite(Number(n)) ? Math.min(max, Math.max(min, Number(n))) : fallback; this.data.github = merge(defaults.github, this.data.github || {}); this.data.updates = merge(defaults.updates, this.data.updates || {}); this.data.github.owner = String(this.data.github.owner || '').trim(); this.data.github.repo = String(this.data.github.repo || '').trim(); this.data.github.branch = String(this.data.github.branch || 'main').trim() || 'main'; this.data.github.versionsRoot = String(this.data.github.versionsRoot || 'sürümler').replace(/^\/+|\/+$/g, '') || 'sürümler'; this.data.microsoftClientId = String(this.data.microsoftClientId || '').trim(); this.data.minMemoryMb = clamp(this.data.minMemoryMb, 512, 131072, 1024); this.data.maxMemoryMb = clamp(this.data.maxMemoryMb, this.data.minMemoryMb, 131072, 4096); this.data.width = clamp(this.data.width, 640, 16384, 1280); this.data.height = clamp(this.data.height, 360, 16384, 720); if (!Array.isArray(this.data.javaArgs)) this.data.javaArgs = []; if (!Array.isArray(this.data.gameArgs)) this.data.gameArgs = []; if (!this.data.client || typeof this.data.client !== 'object') this.data.client = clone(defaults.client); this.data.client = merge(defaults.client, this.data.client); this.data.client.scale = clamp(this.data.client.scale, 0.5, 2, 1); this.data.client.zoomFactor = clamp(this.data.client.zoomFactor, 1.1, 12, 4); this.data.client.lowFireOffset = clamp(this.data.client.lowFireOffset, 0, 1.5, 0.45); this.data.client.timeOfDay = Math.round(clamp(this.data.client.timeOfDay, 0, 23999, 6000)); const hit = Number(this.data.client.hitColor); this.data.client.hitColor = Number.isInteger(hit) ? (hit | 0) : -43691; if (!this.data.client.positions || typeof this.data.client.positions !== 'object' || Array.isArray(this.data.client.positions)) this.data.client.positions = {}; }
}
module.exports = { ConfigStore, merge };
